#!/usr/bin/env python3
"""Report on the I$ shadow model's per-block record (tb/icache_shadow.sv).

The shadow model classifies every I$ probe against an idealized cache of the
same geometry that never drops a fill, so a "phantom" miss is one the core
took on a block that should still have been resident. This script turns the
raw icache_shadow.log into something readable: block addresses joined against
the test's disassembly so the offending code has a name, sorted worst-first.

Pass two logs to compare two runs side by side - the intended use is the
in-order core (the control group, which only cancels on a resolved mispredict)
against Lightning.

    make sim TEST=tests/c/fibi.c CORE=inorder   SIM=vcs \\
            PARAMS='+define+ICACHE_SHADOW' OUTPUT_BASE_DIR=output-io
    make sim TEST=tests/c/fibi.c CORE=lightning SIM=vcs \\
            PARAMS='+define+ICACHE_SHADOW' OUTPUT_BASE_DIR=output-ltg
    scripts/icache_shadow_report.py output-io/vcs/icache_shadow.log \\
            output-ltg/vcs/icache_shadow.log --disas tests/c/fibi.disassembly.s

The disassembly is regenerated by every `make sim` (Makefile's
%.disassembly.s rule), so it is always available next to the test source.
"""

import argparse
import re
import sys
from pathlib import Path

# "# totals: probes=16480 real_miss=858 ..." - the summary the RTL writes.
TOTALS_RE = re.compile(r"^#\s*totals:\s*(.*)$")
CORE_RE = re.compile(r"^#\s*I\$ shadow per-block record, core (\S+)")
GEOMETRY_RE = re.compile(r"^#\s*geometry:\s*(.*)$")

# "0x004000a0  841  841  1  840  96"
FIELDS = ("probes", "real_miss", "shadow_miss", "phantom", "first_cycle")

# "00400014 <fibi>:" - objdump's symbol headers, with -M numeric,no-aliases.
SYMBOL_RE = re.compile(r"^([0-9a-fA-F]+)\s+<([^>]+)>:")
# "  400014:\t02050c63          \tbeq\tx10,x0,40004c <fibi+0x38>"
INSN_RE = re.compile(r"^\s*([0-9a-fA-F]+):\s+[0-9a-fA-F]+\s+\t?(.*)$")


class ShadowLog:
    """One core's per-block record."""

    def __init__(self, path):
        self.path = Path(path)
        self.core = self.path.stem
        self.geometry = ""
        self.totals = {}
        self.blocks = {}
        self._parse()

    def _parse(self):
        with self.path.open() as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue

                if line.startswith("#"):
                    m = CORE_RE.match(line)
                    if m:
                        self.core = m.group(1)
                        continue
                    m = GEOMETRY_RE.match(line)
                    if m:
                        self.geometry = m.group(1)
                        continue
                    m = TOTALS_RE.match(line)
                    if m:
                        for pair in m.group(1).split():
                            if "=" in pair:
                                key, _, val = pair.partition("=")
                                self.totals[key] = int(val)
                    continue

                parts = line.split()
                if len(parts) != 1 + len(FIELDS):
                    continue
                addr = int(parts[0], 16)
                self.blocks[addr] = dict(zip(FIELDS, (int(p) for p in parts[1:])))

    def total(self, key):
        return self.totals.get(key, 0)


def load_symbols(disas_path):
    """Map every instruction address to (symbol, offset) from a disassembly."""
    symbols = {}
    current = None
    current_base = 0

    with open(disas_path) as f:
        for line in f:
            m = SYMBOL_RE.match(line)
            if m:
                current_base = int(m.group(1), 16)
                current = m.group(2)
                continue
            m = INSN_RE.match(line)
            if m and current is not None:
                addr = int(m.group(1), 16)
                # Squash objdump's tab-separated mnemonic/operands into one field
                text = " ".join(m.group(2).split())
                symbols[addr] = (current, addr - current_base, text)

    return symbols


def describe(addr, symbols, block_words):
    """Name a block by the symbols its words fall in."""
    if not symbols:
        return ""

    names = []
    for i in range(block_words):
        entry = symbols.get(addr + 4 * i)
        if entry is None:
            continue
        name, off, _ = entry
        label = f"{name}+0x{off:x}"
        if not names:
            names.append(label)
        elif names[-1].split("+")[0] != name:
            names.append(label)

    return " .. ".join(names) if names else "(not in the disassembly)"


def block_words(log):
    m = re.search(r"x\s*(\d+)\s*words", log.geometry)
    return int(m.group(1)) if m else 4


def print_summary(logs):
    keys = [
        ("probes", "distinct probes"),
        ("real_miss", "real miss events"),
        ("miss_cycles", "real miss cycles (PERF's figure)"),
        ("shadow_miss", "ideal misses (the floor)"),
        ("phantom", "PHANTOM misses"),
        ("pessimistic", "pessimistic (self-check)"),
        ("cancels", "cancel pulses"),
    ]

    width = max(len(label) for _, label in keys)
    header = " ".join(f"{log.core:>14}" for log in logs)
    print(f"{'':{width}}  {header}")
    for key, label in keys:
        row = " ".join(f"{log.total(key):>14,}" for log in logs)
        print(f"{label:{width}}  {row}")

    # The self-check is only binding while nothing has been evicted; say so
    # rather than letting a reader over-trust a nonzero count.
    for log in logs:
        if log.total("pessimistic"):
            print(
                f"\nnote: {log.core} reports {log.total('pessimistic')} "
                "pessimistic classifications. That is expected only once the "
                "cache starts evicting (the two LRU states diverge); on a "
                "workload that fits, it means the model is misaligned."
            )


def print_blocks(logs, symbols, limit):
    words = block_words(logs[0])
    all_addrs = set()
    for log in logs:
        all_addrs.update(log.blocks)

    def worst(addr):
        return max(log.blocks.get(addr, {}).get("phantom", 0) for log in logs)

    ordered = sorted(all_addrs, key=lambda a: (-worst(a), a))[:limit]

    print("\nper-block, worst phantom count first")
    per_core = "".join(f"{log.core + ' probes':>18}{'miss':>8}{'phantom':>9}"
                       for log in logs)
    print(f"{'block':<12}{per_core}  code")
    for addr in ordered:
        cells = ""
        for log in logs:
            b = log.blocks.get(addr)
            if b is None:
                cells += f"{'-':>18}{'-':>8}{'-':>9}"
            else:
                cells += (f"{b['probes']:>18,}{b['real_miss']:>8,}"
                          f"{b['phantom']:>9,}")
        print(f"0x{addr:08x}{cells}  {describe(addr, symbols, words)}")


def main():
    parser = argparse.ArgumentParser(
        description="Report on tb/icache_shadow.sv's per-block record.")
    parser.add_argument("logs", nargs="+", metavar="icache_shadow.log",
                        help="one or two shadow logs (two = side by side)")
    parser.add_argument("--disas", metavar="FILE",
                        help="test disassembly, to name the offending blocks")
    parser.add_argument("--limit", type=int, default=20,
                        help="how many blocks to list (default 20)")
    args = parser.parse_args()

    if len(args.logs) > 2:
        parser.error("at most two logs can be compared at once")

    try:
        logs = [ShadowLog(p) for p in args.logs]
    except OSError as e:
        sys.exit(f"error: {e}")

    if not any(log.blocks for log in logs):
        sys.exit("error: no per-block records found; was the run built with "
                 "PARAMS='+define+ICACHE_SHADOW'?")

    symbols = {}
    if args.disas:
        try:
            symbols = load_symbols(args.disas)
        except OSError as e:
            print(f"warning: {e}; blocks will not be named", file=sys.stderr)

    print(f"geometry: {logs[0].geometry}")
    print_summary(logs)
    print_blocks(logs, symbols, args.limit)

    # The headline: how much of the miss count was avoidable.
    print()
    for log in logs:
        real = log.total("real_miss")
        if real:
            pct = 100.0 * log.total("phantom") / real
            print(f"{log.core}: {log.total('phantom'):,} of {real:,} I$ misses "
                  f"({pct:.1f}%) were avoidable - the block was already fetched "
                  f"and should have still been resident.")


if __name__ == "__main__":
    main()
